### ISSUE TITLE
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

### ISSUE THREAD

**Issue by GeneralJing** [foolwood/pytorch-slimming#12]
Traceback (most recent call last):
  File "main.py", line 152, in <module>
    train(epoch)
  File "main.py", line 120, in train
    100. * batch_idx / len(train_loader), loss.data[0]))
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

**Comment by shine0801** [comment]
I have the same problem. Has it been solved?

**Comment by 1337Eddy** [comment]
That's a version problem. Replace `100. * batch_idx / len(train_loader), loss.data[0]))` in line 120 with `100. * batch_idx / len(train_loader), loss.data.item()))` and `test_loss += F.cross_entropy(output, target, size_average=False).data[0]` in line 131 with `test_loss += F.cross_entropy(output, target, size_average=False).data.item()`
