### ISSUE TITLE
Pruned error

### ISSUE THREAD

**Issue by LXWDL** [foolwood/pytorch-slimming#2]
Thank you for sharing, I encountered the following error in the implementation of the following code,
python prune.py --model model_best.pth.tar --save pruned.pth.tar --percent 0.7
error:
Traceback (most recent call last):
  File "prune.py", line 120, in <module>
    m1.weight.data = m0.weight.data[idx1].clone()
TypeError: indexing a tensor with an object of type numpy.ndarray. The only supported types are integers, slices, numpy scalars and torch.cuda.LongTensor or torch.cuda.ByteTensor as the only argument.
I am not very familiar with Pytorch, do not know how to solve, can you help me fix this bug? Thanks for your help, I use Python 2.7.14, Pytorch 0.20

**Comment by angelamin** [comment]
Ｉ meet the same error, have you solved it? thanks for your reply

**Comment by LXWDL** [comment]
Not yet,the following error occurred when I used the Pytorch 1.2 version:
Traceback (most recent call last):
   File "prune.py", line 47, in <module>
     Total = m.weight.data.shape[0]
AttributeError: 'torch.cuda.FloatTensor' object has no attribute 'shape'

**Comment by LXWDL** [comment]
Not yet, the following error occurred when I used the version of Pytorch 0.1.12:
Traceback (most recent call last):
   File "prune.py", line 47, in <module>
     Total = m.weight.data.shape[0]
AttributeError: 'torch.cuda.FloatTensor' object has no attribute 'shape'

**Comment by Coderx7** [comment]
@angelamin ,@LXWDL: Did you solve this issue? I'm facing the very same error. I'm on pytorch 0.3.1

**Comment by struggle5101** [comment]
@LXWDL @angelamin 
I meet the same error, and I change it to:
        thre=thre.to('cuda:0')
        mask = weight_copy.abs().gt(thre).float()
and it is solved.

**Comment by naranglovish** [comment]
@LXWDL @struggle5101 @Coderx7 @angelamin 
I am getting this error

  File "prune.py", line 131, in <module>
    w = m0.weight.data[:, idx0, :, :].clone()
IndexError: When performing advanced indexing the indexing objects must be LongTensors or convertible to LongTensors

Can anybody help??

**Comment by Coderx7** [comment]
@naranglovish : Use [this port](https://github.com/Eric-mingjie/network-slimming) instead.

**Comment by chuliuT** [comment]
> @LXWDL @struggle5101 @Coderx7 @angelamin
> I am getting this error
> 
> File "prune.py", line 131, in
> w = m0.weight.data[:, idx0, :, :].clone()
> IndexError: When performing advanced indexing the indexing objects must be LongTensors or convertible to LongTensors
> 
> Can anybody help??

i met the same Q
In this link :[slim](https://github.com/Eric-mingjie/network-slimming/blob/master/vggprune.py)
replace code under below,it should be works
elif isinstance(m0, nn.Conv2d):
        idx0 = np.squeeze(np.argwhere(np.asarray(start_mask.cpu().numpy())))
        idx1 = np.squeeze(np.argwhere(np.asarray(end_mask.cpu().numpy())))
        print('In shape: {:d}, Out shape {:d}.'.format(idx0.size, idx1.size))
        if idx0.size == 1:
            idx0 = np.resize(idx0, (1,))
        if idx1.size == 1:
            idx1 = np.resize(idx1, (1,))
        w1 = m0.weight.data[:, idx0.tolist(), :, :].clone()
        w1 = w1[idx1.tolist(), :, :, :].clone()
        m1.weight.data = w1.clone()
