### ISSUE TITLE
error:torch.load

### ISSUE THREAD

**Issue by fanbinqi** [foolwood/pytorch-slimming#4]
when i reload the model_best.pth.tar, i got this error:
=> loading checkpoint './model_best.pth.tar'
Traceback (most recent call last):
  File "prune.py", line 37, in <module>
    model.load_state_dict(checkpoint['state_dict'])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.feature.0.weight" in state_dict'

how can i solve this problem???

**Comment by fanbinqi** [comment]
I use python 3.5.2 and Pytorch 0.3.1
