### ISSUE TITLE
IndexError: index 0 is out of bounds for dimension 0 with size 0' in Prune.py

### ISSUE THREAD

**Issue by rrryan2016** [foolwood/pytorch-slimming#9]
Hey, thx for the code released. 

I follow the steps in the READEME file, as `python main.py` in the first, and then, intend to run `python prune.py --model model_best.pth.tar --save pruned.pth.tar --percent 0.7` but I encounter the error as below

Traceback (most recent call last):
  File "prune.py", line 110, in <module>
    newmodel = vgg(cfg=cfg)
  File "/home/amax/users/liuwenzhe/pruning/pytorch-slimming/vgg.py", line 13, in __init__
    self.feature = self.make_layers(cfg, True)
  File "/home/amax/users/liuwenzhe/pruning/pytorch-slimming/vgg.py", line 31, in make_layers
    conv2d = nn.Conv2d(in_channels, v, kernel_size=3, padding=1, bias=False)
  File "/home/amax/anaconda3/envs/lwz36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 332, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/home/amax/anaconda3/envs/lwz36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 46, in __init__
    self.reset_parameters()
  File "/home/amax/anaconda3/envs/lwz36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 49, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/amax/anaconda3/envs/lwz36/lib/python3.6/site-packages/torch/nn/init.py", line 310, in kaiming_uniform_
    fan = _calculate_correct_fan(tensor, mode)
  File "/home/amax/anaconda3/envs/lwz36/lib/python3.6/site-packages/torch/nn/init.py", line 279, in _calculate_correct_fan
    fan_in, fan_out = _calculate_fan_in_and_fan_out(tensor)
  File "/home/amax/anaconda3/envs/lwz36/lib/python3.6/site-packages/torch/nn/init.py", line 211, in _calculate_fan_in_and_fan_out
    receptive_field_size = tensor[0][0].numel()
IndexError: index 0 is out of bounds for dimension 0 with size 0

I checked the cfg in `newmodel = vgg(cfg=cfg)`, and it printed as 

`[53, 64, 'M', 128, 128, 'M', 256, 256, 254, 212, 'M', 34, 1, 1, 0, 'M', 0, 0, 1, 263]`

I guess the error may lie in 0, and confuses the nn.Conv2d(). 

What can I do to fix it?  Is it necessary to train it again? 

Thx in advance.

**Comment by rrryan2016** [comment]
Update:
I re-run the `python main.py -sr --s 0.0001`, and then, run the `prune.py` successfully without any 0 in `cfg`.
